version: '3.5'



networks:
  panaceia:



services:
  mongodb:
    container_name: mongodb
    hostname: mongodb
    restart: always
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    networks: 
      - panaceia
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.runCommand(\"ping\").ok' localhost:27017/test --quiet || echo OK"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    image: rabbitmq:3.6.10-management
    environment:
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    ports:
      - "15672:15672"
      - "5672:5672"
    networks: 
      - panaceia
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status | grep pid"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
